-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 22:27:17 2017
-- Model: webapi_stub    Version: 1.2.0

-- -----------------------------------------------------
-- Table `webapi_stub`.`responses`
-- -----------------------------------------------------
ALTER TABLE `webapi_stub`.`responses`
ADD COLUMN `sleep_time_seconds` INT(11) NOT NULL DEFAULT 0 COMMENT 'スリープ時間（デフォルト：0秒）' AFTER `http_status_code`;
