-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 22:18:40 2017
-- Model: webapi_stub    Version: 1.3.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `webapi_stub`.`responses`
-- -----------------------------------------------------
UPDATE `webapi_stub`.`responses` SET responses.actions_id = (SELECT actions_id FROM `webapi_stub`.`action_response_joins` where responses.id = action_response_joins.responses_id);
UPDATE `webapi_stub`.`responses` SET responses.actions_id = 0 WHERE responses.actions_id is null;
