-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 22:18:40 2017
-- Model: webapi_stub    Version: 1.3.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `webapi_stub`.`responses`
-- -----------------------------------------------------
ALTER TABLE `webapi_stub`.`responses` 
CHANGE COLUMN `actions_id` `actions_id` BIGINT(20) NOT NULL COMMENT 'アクションID（※紐付け可能なアクションIDを指定。）' ;

CREATE INDEX `fk_responses_actions1_idx` ON `webapi_stub`.`responses` (`actions_id` ASC);
